contact_links:
    - name: Feature request
      url: https://github.com/orgs/primefaces/discussions/categories/primeng
      about: Propose an enhancement at discussions.
    - name: Support
      url: https://primereact.org/support/
      about: Professional support for the open source innovation.
